### ISSUE TITLE
typedef'd Types Do Not Work At The Moment

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [WindhoverLabs/juicer#2]
At the moment, types such as `typedef int16 my_int` do *not* work. We will invistigate this issue in the future, however, it is not a priority at the moment. 
Beware typdef'd structs DO work at the moment; it appears to be a problem specific to typdef'd intrinsic types.

**Comment by mVanSteen** [comment]
Hello, I was wondering if there was any update since this issue was opened ? 

I will add that the some typedef with struct do not work either : 
 - Typedef referring directly to another struct 
   for example with the line
   `typedef CFE_ES_NoArgsCmd_t CFE_ES_NoopCmd_t;`
  CFE_ES_NoopCmd_t will have no declared fields 
 - Typedef where the struct was named 
 for example with the lines
```
typedef struct CFE_ES_FileNameCmd_Payload
{
    char FileName[CFE_MISSION_MAX_PATH_LEN]; 
} CFE_ES_FileNameCmd_Payload_t;
```
CFE_ES_FileNameCmd_Payload_t will have no declared fields 

Thank you for the help

**Comment by lorenzo-gomez-windhover** [comment]
@mVanSteen This issues is a bit misleading (sorry about that; sometimes I write these as notes and forget to close them!). I believe this should answer your question:https://github.com/WindhoverLabs/auto-yamcs/issues/79#issuecomment-1843149110


Please let me know if you run into any issues.

**Comment by mVanSteen** [comment]
Okay, thank you very much for the clarification. If I understand correctly, there is no way to avoid type_remaps in the case of typedefs (or at least automate the process).
Once again thank you very much for all the work you have done, saving us a tremendous amount of time

**Comment by lorenzo-gomez-windhover** [comment]
> Okay, thank you very much for the clarification. If I understand correctly, there is no way to avoid type_remaps in the case of typedefs (or at least automate the process).

Apologies for taking so long to reply. Yes, at the moment this is the case. And a lot of it comes down to scoping juicer. The way we get these bit patterns is from the DWARF4 standard and the [spec](https://dwarfstd.org/dwarf4std.html) is _gigantic_ so we didn't want to spend years and years implementing all the possible types in  DWARF (this gets worse with a language like C++ which has all kinds of fancy/complicated features like inheritance).  We scoped it to the needs of something like CFS, which satisfies our needs just fine.  But please don't let this discourage you from reporting any other edge cases you come across. Always love to hear (and if time allows, look for solutions) about issues people using these tools run into.

Hopefully this clarifies any confusion.

**Comment by lorenzo-gomez-windhover** [comment]
Sorry, misunderstood the issue here...
The following struct _should_ work if you give it to Juicer:

```
typedef struct CFE_ES_FileNameCmd_Payload
{
    char FileName[CFE_MISSION_MAX_PATH_LEN]; 
} CFE_ES_FileNameCmd_Payload_t;
```
It'll really help, if possible, if I could look at the ouput sqlite file that you generated from your binaries.

**Comment by lorenzo-gomez-windhover** [comment]
@mVanSteen There shouldn't be a need anymore for the "type_remaps" in the case of typedef'd intrinsic types after the changes in https://github.com/WindhoverLabs/xtce_generator/commit/d3e6b536f27fd973f83d3b8fdf96a8c6342e6874 and https://github.com/WindhoverLabs/juicer/commit/282a1afb5b6c9327d232b3c2b9f6e67a7ab47141. Essentially the xtce tool now is able to "follow" the typedef'd types in the DB.
